### ISSUE TITLE
truestring/falsestring arguments appear not to set these options

### ISSUE THREAD

**Issue by MichaeLeroy** [JuliaData/CSV.jl#228] opened 2018-07-12 23:44 UTC
I'm a longtime DataFrames user working to replace `readtable` with `CSV.read`.  Because I'm reading large tables that have some sparsely populated columns, making type detection problematic, I elected to define `types`, which in turn prompted me to try to read my Boolean columns using the truestring/falsestring options.  I get a parse error when I do so:

```julia
julia> ncrash = CSV.read(extractFN("crash"); types=coldef, delim='~', truestring="Y", falsestring="N")
ERROR: BoundsError: attempt to access 0-element Array{UInt8,1} at index [1]
Stacktrace:
 [1] parsefield(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Type{Bool}, ::CSV.Options{DateFormat{Symbol("yyyy-mm-dd\\THH:
```

Playing around, I tried setting up a `CSV.Source`:

```julia
julia> CSV.Source(extractFN("crash"); types=coldef, delim='~', truestring="Y", falsestring="N")
CSV.Source: crash.csv
    CSV.Options:
        delim: '~'
        quotechar: '"'
        escapechar: '\\'
        missingstring: ""
        dateformat: dateformat"yyyy-mm-ddTHH:MM:SS.s"
        decimal: '.'
        truestring: 'true'
        falsestring: 'false'
        internstrings: true
Data.Schema:
rows: 70330  cols: 215
Columns:
 "CRSHNMBR"  Int64
 "RECDNMBR"  Int64
 "RECDSTAT"  String
```
Which indicates that, contrary to my efforts to customize, `truestring="true"` and `falsestring="false"`.  This discrepancy might easily account for parse errors.  

I followed up with 2 checks.  

I took a 10 line sample of my input file and edited it, replacing `Y` with `true` and `N` with `false`.  I was able to `CSV.read` this modified file successfully, regardless of whether I used the Boolean string options.

I changed my `types` specification to read the `Bool` columns instead as `String`.  Taking that less ambitious approach, I was able to read the entire data file without a problem.

All this seems to point to a problem with setting the `truestring` and `falsestring`.  (Though the problem could be with me.)

Version Information:

```julia
julia> versioninfo()
Julia Version 0.6.3
Commit d55cadc350* (2018-05-28 20:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

julia> Pkg.status("CSV")
 - CSV                           0.2.5

julia> Pkg.status("DataFrames")
 - DataFrames                    0.11.6

julia> Pkg.status("Missings")
 - Missings                      0.2.10
```

**Comment by nalimilan** [comment] 2018-07-13 16:17
That's really weird: it works here with CSV 0.2.5 on Julia 0.6.3. I really don't know what could explain this difference. Can you provide a small file to reproduce the problem, and the contents of `coldef`?

**Comment by quinnj** [comment] 2018-08-03 13:47
Yes, it'd be ideal if you could share the original file and exact commands that were causing the issue (I can provide an email if you'd like to only share privately). This should also be improved in #232 in any case, so it might be worth trying on that branch (or once it's been merged).

**Comment by quinnj** [comment] 2018-08-29 13:20
The code for this has been merged in master; right now it's accessible through the `CSV.File(file; kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`.

For `CSV.File`, the keyword arguments have been changed to `truestrings` and `falsestrings`, since they both support specifying multiple strings to be used for detecting `true` and `false` values.

**Closed by quinnj** 2018-08-29 13:20 UTC
