### ISSUE TITLE
CSV.read() throws a Parsing exception while readtable() doesn't.

### ISSUE THREAD

**Issue by mystis666** [JuliaData/CSV.jl#227] opened 2018-07-12 17:28 UTC
Hello everyone, I'm trying to open the data from this dataset : https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

to a Jupyter Notebook with Julia 0.6.3.

It has missing values and different columns have String, Float or Int as type so one will often find Union{Missing.Missing,*something*} as the type for that column.

Basically, what's going on is that even though I get a deprecation warning, readtable() manages to create a DataFrame just fine from the csv files.

when I do : 

train = readtable("C:\\User\\Me\\Data\\train.csv")

 for example it's alright.

But when I try the exact same wit CSV.read() I get : 

"CSV.ParsingException("error parsing a `Int64` value on column 27, row 235; encountered 'N'")"

Which is weird because that column only contains String values and doesn't have any missing values.

I tried playing around with the arguments but no luck so far.

Does anyone have a clue?

Thanks!

**Comment by nalimilan** [comment] 2018-07-13 16:06
How are missing values represented in the data? I guess using `NA`, so you need to pass `missingstring="NA"`.

**Comment by nalimilan** [comment] 2018-07-13 16:40
OK, so it doesn't work for numeric columns because `"NaN"` is parsed as `NaN` before it gets the chance to be converted to `missing`. Reproducer:
```julia
CSV.read(IOBuffer("a\n0.0\nNaN"), missingstring="NaN")
```
It works for string and integer columns though.

The other problem you have is that your column probably contains only numbers in the first 100 rows, and then a `"NaN"`. Try passing `rows_for_type_detect=1000` or an even higher value, or specifying the type of the column as `Float64` manually. Then you can replace `NaN` with `missing` manually.

**Comment by mystis666** [comment] 2018-07-13 16:50
I'll try that as soon as I get to my computer, thanks a ton for your help !

**Comment by mystis666** [comment] 2018-07-13 22:06
Increasing row type detect help with the training file but for some reason the test file throws a Parsing error as improper type even if row detect is set higher. It says "Int64" even when at the first row of a column, weirdly. Setting column types manually doesn't work when it starts by a missing value. 

I tried playing around with CSV.read() other arguments but it doesn't help

**Comment by nalimilan** [comment] 2018-07-14 09:59
Please be more specific. What happens if you set `rows_for_type_detect` to a value as large as the total number of rows? What exact errors do you get?

**Comment by mystis666** [comment] 2018-07-14 11:50
So when I try to use,

train = CSV.read("C:\\User\\Me\\train.csv",missingstring="NA",rows_for_type_detect=1000)

I get no issues and I have a proper Dataframe to use but with the test set, which is very similar to train.

test = CSV.read("C:\\User\\Me\\test.csv",missingstring="NA",rows_for_type_detect=1459)

I get : 

CSV.ParsingException("error parsing a `Int64` value on column 22, row 1; encountered 'G'")

which is weird because there are not ints in this column, only strings and missing values,

if I manually enter the type of that column, it just does the exact same thing to another one that is only strings, but somehow it expects int64.

I don't really understand what's going on since I don't have that problem for train, where the columns are similarily structured.

**Comment by nalimilan** [comment] 2018-07-14 12:08
OK. Could you post a file which allows reproducing the problem? Since the error happens on the first row, maybe a one-row file would be enough.

**Comment by mystis666** [comment] 2018-07-14 13:23
Yes !, the test.csv from this kaggle competition https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

train offers no issue but test does

**Comment by quinnj** [comment] 2018-08-23 05:50
I have a local branch where no error is thrown.

**Comment by quinnj** [comment] 2018-08-29 13:20
The code for this has been merged in master; right now it's accessible through the `CSV.File(file; kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`

**Closed by quinnj** 2018-08-29 13:20 UTC
