### ISSUE TITLE
Type inconsitency when loading column of strings?

### ISSUE THREAD

**Issue by jbrea** [JuliaData/CSV.jl#290] opened 2018-09-21 11:33 UTC
file1.csv
```
x
"b"
"a"
```
file2.csv
```
x
"b"
"b"
"a"
```

With CSV v0.3.1 (and current master) I get on julia 1.0
```julia
julia> typeof(CSV.read("src/experiments/data/file1.csv")[:x])                                  
Array{Union{Missing, String},1}

julia> typeof(CSV.read("src/experiments/data/file2.csv")[:x])                                  
CategoricalArray{Union{Missing, String},1,UInt32,String,CategoricalString{UInt32},Missing}    
```
If the first `"b"` in file2.csv is replaced by `"c"` I get again `Array{Union{Missing, String},1}`.

Is this intended?

**Comment by nalimilan** [comment] 2018-09-21 11:40
AFAIK that will be fixed very soon on master when `CSV.read` will be ported to `CSV.File`. That's because it will use `categorical=false`, while currently the type depends on the proportion of unique values. I can confirm that `CSV.File` uses a `Union{String,Missing}` column for the second file.

**Comment by quinnj** [comment] 2018-09-22 13:36
Yes, this is fixed on master; new release coming soon.

**Closed by quinnj** 2018-09-22 13:36 UTC
