### ISSUE TITLE
Pre-warming CSV.read

### ISSUE THREAD

**Issue by iaravena** [JuliaData/CSV.jl#128] opened 2017-12-04 19:08 UTC
Hi all,
This is more of a question than an issue, Is there any way to pre-warm CSV.read or maybe compile it ahead-of-time for particular use cases?
My application starts by reading a series of CSV files and it does not read files again. Since the change from readtable (DataFrames) to CSV.read, following a deprecation warning, read times went from 43 secs to 500 secs.
I have tried passing the types of each column and also reading a just couple of rows, but not success so far for getting the time down. Any suggestions are welcome.

**Comment by nalimilan** [comment] 2017-12-05 21:33
Maybe a duplicate of https://github.com/JuliaData/CSV.jl/issues/127. Can you post the version of Julia, CSV and DataStreams you are using? Also, what does the CSV file you read look like?

**Comment by quinnj** [comment] 2018-01-06 08:04
Please reopen if you can still reproduce

**Comment by iaravena** [comment] 2018-01-06 14:14
[testfile.csv.zip](https://github.com/JuliaData/CSV.jl/files/1608837/testfile.csv.zip)
Apologies for going on without providing further details. The file above is the type of file that I need to read (the actual instances has100x more rows). Timing CSV.read in Julia 0.6.0 with CSV 0.2.0 gives me

```
@time CSV.read("testfile.csv")
130.709533 seconds (11.22 M allocations: 415.608 MiB, 0.34% gc time)
```

the first time and 

```
@time CSV.read("testfile.csv")
0.076419 seconds (187.64 k allocations: 3.725 MiB)
```
after warming up. For a comparison, using R this file can be read very fast the first time

```
system.time(detprof <- read.csv("testfile.csv"))
   user  system elapsed 
  0.076   0.004   0.081 
```

The problem is that I only read the files once, so times after warming up don't matter that much. For the moment I got around this problem by writing my own reader based on readdlm, but on the long run it would be useful to have a black box reader capable of handling this type of files efficiently enough without warming up.

**Comment by quinnj** [comment] 2018-01-06 14:55
Thanks for sharing the file. I'll dig in and see what we can do here.

**Comment by quinnj** [comment] 2018-08-29 13:46
This is fixed on master with the switch to `CSV.File` (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon).

The first run of this dataset now takes 1-3s for me with a faster 2nd run.

Note for now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`

**Closed by quinnj** 2018-08-29 13:46 UTC
