### ISSUE TITLE
using CSV became extremly slow

### ISSUE THREAD

**Issue by ufechner7** [JuliaData/CSV.jl#324] opened 2018-10-13 11:32 UTC
With the latest version of CSV the load time on Julia 1.0.1 and Julia 0.7 increased 10 times:
```
  | | |_| | | | (_| |  |  Version 1.0.1 (2018-09-29)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time using CSV
 26.338247 seconds (43.67 M allocations: 2.136 GiB, 5.79% gc time)
```
Same machine:
```
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> @time using CSV
  2.881148 seconds (2.54 M allocations: 146.385 MiB, 11.33% gc time)
```
It used to be faster on 0.7 then on 0.6.

Any idea?

**Comment by nalimilan** [comment] 2018-10-13 16:09
The codebase has changed a lot in the last few months, so it's probably just due to that.

**Comment by ufechner7** [comment] 2018-10-13 22:03
We are mainly do flight testing of wind drones. After each flight (they are usually short, like 10 min) we analyse the csv log file, which is not small, because we are logging about 120 values at 200 Hz. With Julia 0.6 loading a log file and preprocessing it takes about 20s on my laptop. I will create a more realistic test for loading CSV and loading the data to see how much slower the current version of CSV is compared to the 0.2.5 version that I used with Julia 0.6.

**Comment by nalimilan** [comment] 2018-10-14 11:17
Then it shouldn't make a difference for you whether compilation happens when loading the package or when reading a file for the first time. In the end the total time should be similar. You can easily check that by removing the call I linked to above.

**Comment by quinnj** [comment] 2018-10-15 23:31
The CSV.jl-induced regression is at least fixed on master now.

**Closed by quinnj** 2018-10-15 23:31 UTC
