### ISSUE TITLE
Support empty string delimiter

### ISSUE THREAD

**Issue by guyvdbroeck** [JuliaData/CSV.jl#748] opened 2020-10-10 05:34 UTC
I have data files that don't have any delimiter: each character is its own column.
It would be great if `CSV.jl` could support empty string delimiters: `CSV.File("data.txt"; delim="")`
Currently it puts the entire row string into one column.

**Comment by quinnj** [comment] 2020-10-21 02:43
I'm not sure I really see the value of using CSV.jl here, when it seems like all you need is something like:
```julia
open(file) do io
    line = readline(io)
    cols = [[line[i]] for i = 1:length(line)]
    for line in eachline(io)
        for i = 1:length(line)
            push!(cols[i], line[i])
        end
    end
end
```
But perhaps if we come up with some kind of API/framework for more general fixed width parsing, it could help here; I'm going to close for now as a duplicate of #601 . Feel free to comment here with other questions or to walk through your use-case in more detail if I'm misunderstanding something here.

**Closed by quinnj** 2020-10-21 02:43 UTC
