### ISSUE TITLE
CSV.Chunks crashing on large CSV

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CSV.jl#734] opened 2020-08-28 11:09 UTC
I am using the Fannie Mae performance 2003Q3 dataset from https://docs.rapids.ai/datasets/mortgage-data

```
using CSV, JDF
for (i, chunk) in enumerate(CSV.Chunks("c:/data/Performance_2003Q3.txt"; tasks = 12, header=0))
    JDF.save("csv_chunk_$i.jdf", DataFrame!(chunk))
end
```

This is what I see on my Windows 10 machine with 64G of RAM

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x32e0a713 -- getindex at .\array.jl:809 [inlined]
peekbyte at C:\Users\RTX2080\.julia\packages\Parsers\DAskp\src\utils.jl:220 [inlined]
xparse at C:\Users\RTX2080\.julia\packages\Parsers\DAskp\src\strings.jl:282 [inlined]
findrowstarts! at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\detection.jl:321
in expression starting at REPL[11]:1
getindex at .\array.jl:809 [inlined]
peekbyte at C:\Users\RTX2080\.julia\packages\Parsers\DAskp\src\utils.jl:220 [inlined]
xparse at C:\Users\RTX2080\.julia\packages\Parsers\DAskp\src\strings.jl:282 [inlined]
findrowstarts! at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\detection.jl:321
multithreadparse at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\file.jl:420
unknown function (ip: 0000000032A8BFC8)
#File#27 at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\file.jl:258
Type##kw at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\file.jl:229
unknown function (ip: 0000000032A89A81)
iterate at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\chunks.jl:85
iterate at .\iterators.jl:139
unknown function (ip: 0000000032AEC41D)
top-level scope at .\REPL[11]:2
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:834
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:790
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:790
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:790
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:849 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:883
eval at .\boot.jl:331
eval_user_input at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:134
repl_backend_loop at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:195
start_repl_backend at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:180
#run_repl#37 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:292
run_repl at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:288
#806 at .\client.jl:399
jfptr_YY.806_45542.clone_1 at C:\Users\RTX2080\AppData\Local\Programs\Julia 1.5.1\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:710 [inlined]
invokelatest at .\essentials.jl:709 [inlined]
run_main_repl at .\client.jl:383
exec_options at .\client.jl:313
_start at .\client.jl:506
jfptr__start_31861.clone_1 at C:\Users\RTX2080\AppData\Local\Programs\Julia 1.5.1\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
true_main at /cygdrive/d/buildbot/worker/package_win64/build/ui\repl.c:106
wmain at /cygdrive/d/buildbot/worker/package_win64/build/ui\repl.c:227
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-7.0.0-1/crt\crtexe.c:334
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-7.0.0-1/crt\crtexe.c:223
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 245466625 (Pool: 245426537; Big: 40088); GC: 113
```

**Comment by hdavid16** [comment] 2020-08-29 16:10
Getting a similar output with CSV.write on a large dataset: https://github.com/JuliaData/CSV.jl/issues/735#issue-688559890

**Comment by quinnj** [comment] 2020-10-29 07:01
@xiaodaigh , can you still reproduce this? I wonder if it's windows-specific or something. I've tried a variety of task combinations and haven't run into any issues on OSX.

**Comment by xiaodaigh** [comment] 2020-10-29 10:02
Yep. Still reproducicble on the master branch of CSV on both Windows 10 and Ubuntu 20.04

**Comment by quinnj** [comment] 2020-10-29 17:22
Alright, after dusting off an old windows box, I was able to reproduce and find a fix here: https://github.com/JuliaData/CSV.jl/pull/763

**Comment by quinnj** [comment] 2020-10-29 23:15
@xiaodaigh , just merged the fix to master; would you mind confirming that your cases windows/ubuntu are fixed?

**Closed** 2020-10-29 23:14 UTC

**Comment by xiaodaigh** [comment] 2020-10-30 02:45
I still get this error

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x9a70d18 -- xparse at C:\Users\RTX2080\.julia\packages\Parsers\dOIit\src\strings.jl:0 [inlined]
findrowstarts! at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\detection.jl:321
in expression starting at REPL[7]:1
xparse at C:\Users\RTX2080\.julia\packages\Parsers\dOIit\src\strings.jl:0 [inlined]
findrowstarts! at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\detection.jl:321
multithreadparse at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\file.jl:420
unknown function (ip: 0000000025D76338)
#File#27 at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\file.jl:258
Type##kw at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\file.jl:229
unknown function (ip: 0000000025D747C1)
iterate at C:\Users\RTX2080\.julia\packages\CSV\MKemC\src\chunks.jl:85
iterate at .\iterators.jl:139
unknown function (ip: 0000000025DA9C2D)
abc at .\REPL[6]:4
unknown function (ip: 0000000025D68B43)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:117
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:206
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:157 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:548
jl_interpret_toplevel_thunk at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:660
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:840
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:790
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:790
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:790
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:849 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:883
eval at .\boot.jl:331
eval_user_input at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:134
repl_backend_loop at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:195
start_repl_backend at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:180
#run_repl#37 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:292
run_repl at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:288
#807 at .\client.jl:399
jfptr_YY.807_82743 at C:\Users\RTX2080\AppData\Local\Programs\Julia 1.5.2\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:710 [inlined]
invokelatest at .\essentials.jl:709 [inlined]
run_main_repl at .\client.jl:383
exec_options at .\client.jl:313
_start at .\client.jl:506
jfptr__start_82363 at C:\Users\RTX2080\AppData\Local\Programs\Julia 1.5.2\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
true_main at /cygdrive/d/buildbot/worker/package_win64/build/ui\repl.c:106
wmain at /cygdrive/d/buildbot/worker/package_win64/build/ui\repl.c:227
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-7.0.0-1/crt\crtexe.c:334
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-7.0.0-1/crt\crtexe.c:223
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 161279254 (Pool: 161270493; Big: 8761); GC: 31
```

**Comment by quinnj** [comment] 2020-10-30 03:01
It looks like you may not be on the latest code judging by the line numbers; can you do `] add CSV#master` and then try?

**Comment by xiaodaigh** [comment] 2020-11-03 01:17
Ok it's working now
