### ISSUE TITLE
Excess columns create offset at each row

### ISSUE THREAD

**Issue by matbesancon** [JuliaData/CSV.jl#239] opened 2018-08-14 13:29 UTC
Easier to explained with an example
```
$ cat test.csv 
```
```julia
a,b,c,d,e
1.0,5.0,3
1.0,5.0,3
1.0,5.0,3
julia> import CSV
julia> CSV.read("test.csv")
3×5 DataFrames.DataFrame
│ Row │ a       │ b       │ c       │ d       │ e       │
│ 1   │ 1.0     │ 5.0     │ 3.0     │ 1.0     │ 5.0     │
│ 2   │ 3.0     │ 1.0     │ 5.0     │ 3.0     │ missing │
│ 3   │ missing │ missing │ missing │ missing │ missing │
```
Expected behavior:
```
3×5 DataFrames.DataFrame
│ Row │ a   │ b   │ c │ d       │ e       │
├─────┼─────┼─────┼───┼─────────┼─────────┤
│ 1   │ 1.0 │ 5.0 │ 3 │ missing │ missing │
│ 2   │ 1.0 │ 5.0 │ 3 │ missing │ missing │
│ 3   │ 1.0 │ 5.0 │ 3 │ missing │ missing │
```

**Comment by nalimilan** [comment] 2018-08-16 14:42
Duplicate of https://github.com/JuliaData/CSV.jl/issues/230.

**Closed by nalimilan** 2018-08-16 14:42 UTC
