### ISSUE TITLE
32-bit numeric types aren't working

### ISSUE THREAD

**Issue by robsmith11** [JuliaData/CSV.jl#612] opened 2020-04-18 14:27 UTC
I'm working with some large tables that have a limited range of values so I wanted to read some columns as 32-bit types.  If I use `CSV.read("/tmp/file.csv", types=[Int32, Float32])`, the columns will be read as `Int64` and `Float64` rather than the types I specified.

**Comment by quinnj** [comment] 2020-04-18 14:47
Duplicate of https://github.com/JuliaData/CSV.jl/issues/431; TL;DR this isn't supported at the moment

**Closed by quinnj** 2020-04-18 14:47 UTC
