### ISSUE TITLE
CSV Validate failing

### ISSUE THREAD

**Issue by bisraelsen** [JuliaData/CSV.jl#195] opened 2018-04-13 22:12 UTC
I am trying to read a file, and `CSV.read` keeps failing. I then have tried to use `CSV.validate` to understand why and get the exact same error, which I cannot interpret. I am hoping for help.

I am particularly perplexed because I created this file with `CSV.write`.
```julia
julia> CSV.validate("logs/net_transition_discount_vary_reference_solver_training.csv")
ERROR: MethodError: no method matching *(::Base.TwicePrecision{Float64}, ::Base.TwicePrecision{Float64})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:424
  *(::Base.TwicePrecision, ::Integer) at twiceprecision.jl:470
  *(::Base.TwicePrecision{R}, ::S<:Number) where {S<:Number, R} at twiceprecision.jl:488
  ...
Stacktrace:
 [1] scale(::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at /home/brett/.julia/v0.6/CSV/src/float.jl:71
 [2] parsefield(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Type{Float64}, ::CSV.Options{Void}, ::Int64, ::Int64, ::Base.RefValue{CSV.ParsingState}, ::CSV.##6#7) at /home/brett/.julia/v0.6/CSV/src/float.jl:208
 [3] parsefield(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Type{Union{Float64, Missings.Missing}}, ::CSV.Options{Void}, ::Int64, ::Int64, ::Base.RefValue{CSV.ParsingState}) at /home/brett/.julia/v0.6/CSV/src/parsefields.jl:130
 [4] validate(::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Void}) at /home/brett/.julia/v0.6/CSV/src/validate.jl:32
 [5] #validate#56(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::String, ::Type{T} where T) at /home/brett/.julia/v0.6/CSV/src/validate.jl:48
 [6] validate(::String) at /home/brett/.julia/v0.6/CSV/src/validate.jl:48
```

**Comment by bisraelsen** [comment] 2018-04-13 22:15
Here is the error from `CSV.read`
```julia
julia> CSV.read("logs/net_transition_discount_vary_reference_solver_training.csv")
ERROR: MethodError: no method matching *(::Base.TwicePrecision{Float64}, ::Base.TwicePrecision{Float64})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:424
  *(::Base.TwicePrecision, ::Integer) at twiceprecision.jl:470
  *(::Base.TwicePrecision{R}, ::S<:Number) where {S<:Number, R} at twiceprecision.jl:488
  ...
Stacktrace:
 [1] scale(::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at /home/brett/.julia/v0.6/CSV/src/float.jl:71
 [2] parsefield(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Type{Float64}, ::CSV.Options{Void}, ::Int64, ::Int64, ::Base.RefValue{CSV.ParsingState}, ::CSV.##6#7) at /home/brett/.julia/v0.6/CSV/src/float.jl:208                                                                                                                                
 [3] macro expansion at /home/brett/.julia/v0.6/DataStreams/src/DataStreams.jl:542 [inlined]
 [4] stream!(::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Void}, ::Type{DataStreams.Data.Field}, ::DataFrames.DataFrameStream{Tuple{Array{Union{Int64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1,Missings.Missing}}}, ::DataStreams.Data.Schema{true,Tuple{Union{Int64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Missings.Missing, WeakRefString{UInt8}}}}, ::Int64, ::NTuple{33,Base.#identity}, ::DataStreams.Data.##15#16, ::Array{Any,1}, ::Type{Ref{(:graphID, :discount, :tprob, :num_exit_nodes, :exit_rwd, :caught_rwd, :sensor_rwd, :avg_degree, :deg_variance, :diam, :max_degree, :N, :E, :its, :e_mcts, :d_mcts, :steps, :repeats, :exit_distance, :pursuer_distance, :X3_1, :X3_2, :mean, :median, :moment_2, :moment_3, :moment_4, :moment_5, :moment_6, :moment_7, :moment_8, :moment_9, :moment_10)}}) at /home/brett/.julia/v0.6/DataStreams/src/DataStreams.jl:614                                                                                                                                                              
 [5] #stream!#17(::Bool, ::Dict{Int64,Function}, ::Function, ::Array{Any,1}, ::Array{Any,1}, ::Function, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Void}, ::Type{DataFrames.DataFrame}) at /home/brett/.julia/v0.6/DataStreams/src/DataStreams.jl:490
 [6] (::DataStreams.Data.#kw##stream!)(::Array{Any,1}, ::DataStreams.Data.#stream!, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Void}, ::Type{DataFrames.DataFrame}) at ./<missing>:0
 [7] #read#43(::Bool, ::Dict{Int64,Function}, ::Bool, ::Array{Any,1}, ::Function, ::String, ::Type{T} where T) at /home/brett/.julia/v0.6/CSV/src/Source.jl:339
 [8] read(::String) at /home/brett/.julia/v0.6/CSV/src/Source.jl:338
```

**Comment by nalimilan** [comment] 2018-04-14 17:31
Can you post an example file to reproduce the problem? Are you using the latest version?

**Comment by bisraelsen** [comment] 2018-04-16 15:39
Here is the file as a `.txt`, Github wouldn't allow as a `.csv`. Also, I tried opening the file with Google sheets, and then re-saving the data as a .csv and that file **is** readable by `CSV.read()`.

[test_data.txt](https://github.com/JuliaData/CSV.jl/files/1915862/test_data.txt)
[gsheets_convert.txt](https://github.com/JuliaData/CSV.jl/files/1916050/gsheets_convert.txt)

One obvious difference between the original and the Gsheets version is that the Gsheets version reduced the precision and modified the notation of floats such as converting `3.40622705544736e24` to `3.41E+24`.

I don't think that should matter though because if I use the `rows` option I can usually read some rows of the file.

**Comment by bisraelsen** [comment] 2018-04-16 17:50
FYI, I am using:
```julia
julia> Pkg.status("CSV")
- CSV                             0.2.4+                master
```

**Comment by rocarvaj** [comment] 2018-05-21 20:48
Hello!
I'm having the same problem here (Julia 0.6.1, CSV 0.2.4). I managed to get to the point in which reading a certain amount of rows works OK, but when reading an additional row it breaks.

Take the file:
[test-file.txt](https://github.com/JuliaData/CSV.jl/files/2024027/test-file.txt)

When doing
```julia
CSV.read("test-file.txt", rows=201)
```
everything works OK.

But with
```julia
CSV.read("test-file.txt", rows=202)
```
it breaks.

An this is the problematic line (row 202):
```
1200,log,app1-2.mps.gz,t1-seed-sm,0,1,1E+75,-249.0,1E+75,1E+75,-249.0,1E+75,0,0,0.0,8652.18086,-1.0,0,0,False,0,0.0,0.0,0,0,,,,,1.0,0.0,,5.07317060797
```

I hope this helps. Thanks!
I was working with pandas and wanted to give Julia a try and I failed right away 😢

**Comment by davidanthoff** [comment] 2018-05-21 21:32
I believe https://github.com/davidanthoff/CSVFiles.jl handles both of the files posted in this thread, so you could use that until things are fixed in CSV.jl

**Comment by quinnj** [comment] 2018-08-29 13:38
This should be fixed on master with a refactoring of internals; the new approach uses the `CSV.File(file; kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`

**Closed by quinnj** 2018-08-29 13:38 UTC

**Comment by Magalame** [comment] 2018-09-20 05:09
I'm using CSV v0.3.1, but when I try

`using Tables; table = CSV.File(file; kwargs...) |> columntable`

it says `UndefVarError: File not defined`

**Comment by quinnj** [comment] 2018-09-20 05:10
@Magalame , `CSV.File` is not on v0.3.1, only master for now. To use it, you'll need to do `add Tables CSV#master`.

**Comment by Magalame** [comment] 2018-09-20 05:18
Thanks!

**Comment by joyceraraujo** [comment] 2018-10-05 14:19
@quinnj  I also would like to be able to use CSV.File but I got the same error `UndefVarError: File not defined`. Could you explain me how I could use this function? I didn't understand well what we must to do. Thanks in advance.

**Comment by quinnj** [comment] 2018-10-05 15:15
You actually don't need `CSV#master` any more since the latest release; as long as you're on version > 0.4.0, then you should have the new `CSV.File` functionality. This all assumes, of course, that you're running Julia 0.7/1.0. (0.6 won't get this functionality)

**Comment by joyceraraujo** [comment] 2018-10-08 12:02
Thanks for your answer. I cannot even to access  `pkg mode` . There's what I got when I have tried: 
` julia> ]
ERROR: ParseError("unexpected \"]\"")
Stacktrace:
 [1] #parse#234(::Bool, ::Bool, ::Function, ::String, ::Int64) at .\parse.jl:222
 [2] (::Base.#kw##parse)(::Array{Any,1}, ::Base.#parse, ::String, ::Int64) at .\<missing>:0
 [3] #parse#235(::Bool, ::Function, ::String) at .\parse.jl:232
 [4] parse(::String) at .\parse.jl:232
 [5] macro expansion at C:\JuliaPro-0.6.2.2\pkgs-0.6.2.2\v0.6\Atom\src\repl.jl:117 [inlined]
 [6] anonymous at .\<missing>:?`

**Comment by nalimilan** [comment] 2018-10-08 12:27
You need to upgrade to Julia 0.7 or 1.0.
