### ISSUE TITLE
Failure of CSV.read() when StatPlots is loaded first

### ISSUE THREAD

**Issue by kescobo** [JuliaData/CSV.jl#253] opened 2018-08-29 15:35 UTC
This is an odd one, no doubt. I've talked to @piever about this, and he doesn't think it's the fault of StatPlots, but I have no idea what's going on. Here's the issue: I have a file where, if I simply do:

```julia
using CSV

CSV.read("my_file.csv")
```

It works (loads in ~5 sec).

However, if instead, I do:

```julia
using StatPlots
using CSV

CSV.read("my_file.csv")
```

Julia hangs. It hangs so hard I can't even ctrl-c to interrupt (and I've waited up to ~30 min). I have to hard restart.

I can

```julia
using CSV

CSV.read("my_file.csv")

using StatPlots

CSV.read("my_file.csv")
```

And it *doesn't* hang. It also *doesn't* hang with some simple CSV files that I've tested with (of note, `my_file.csv` was written with `CSV.write()`). But if I do:

```julia
using CSV

CSV.read("some_small_test_file.csv")

using StatPlots

CSV.read("my_file.csv")
```

It hangs.

I can reproduce this in a clean environment where I've only `add`ed CSV.jl and StatPlots.jl. @piever has also been able to reproduce (I'm happy to share the file via DM for testing).

This morning, I tried using the new overhauled versions. (as suggested on slack: `CSV#master`, `DataFrames#mdavezac-tables_integration`). There's still a problem, but maybe something that points a way to a solution?

```julia
using StatPlots
using CSV
using DataFrames

CSV.read("my_file.csv", DataFrame)
```

hangs, but 

```julia
using StatPlots
using CSV
using DataFrames

CSV.File("my_file.csv") |> DataFrame
```

throws an error:

```
ERROR: MethodError: Cannot `convert` an object of type CSV.File{NamedTuple{(:iamc_id, :age_start_smoking, :age_stopped_smoking, :alcohol_units_week, :anti_ccp_range, :anti_ccp_status, :anti_ccp_value, :asdas_crp, :basdai, :bmi, :crp, :current_alcohol_intake, :dactylitis, :das28_crp, :das28_esr, :diagnosis_at_time_of_asses, :disease_duration_at_time, :enthesitis, :esr, :ethnicity, :final_diagnosis, :final_outcome, :gender, :height_cm, :hla_b27, :ibd, :no_of_cigarettes_per_day, :patient_parents_global_vas, :peripheral_arthritis, :psoriasis, :rf_range, :rf_status, :rf_value, :sjc66, :sjc_28, :smoking_current_ever_never, :smoking_pack_years, :smoking_status, :tjc68, :tjc_28, :uveitis, :weight_kg, :diagnosis),Tuple{Union{Missing, String},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Float64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, String},Union{Missing, String},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, String},Union{Missing, Float64},Union{Missing, String},Union{Missing, Float64},Union{Missing, Int64},Union{Missing, String},Union{Missing, String},Union{Missing, String},Union{Missing, Float64},Union{Missing, String},Union{Missing, String},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, String},Union{Missing, String},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Float64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, String},Union{Missing, Float64},Union{Missing, String}}},false,Base.GenericIOBuffer{Array{UInt8,1}},Parsers.Delimited{Parsers.Quoted{Parsers.Strip{Parsers.Sentinel{typeof(Parsers.defaultparser),Parsers.Trie{0x00,false,missing,2,Tuple{}}}}},Parsers.Trie{0x00,false,missing,8,Tuple{Parsers.Trie{0x2c,true,missing,8,Tuple{}},Parsers.Trie{0x0a,true,missing,8,Tuple{}},Parsers.Trie{0x0d,true,missing,8,Tuple{Parsers.Trie{0x0a,true,missing,8,Tuple{}}}}}}},NamedTuple{(),Tuple{}}} to an object of type DataFrame
Closest candidates are:
  convert(::Type{DataFrame}, ::AbstractArray{T,2} where T) at /Users/kev/.julia/packages/DataFrames/S3NqQ/src/dataframe/dataframe.jl:986
  convert(::Type{DataFrame}, ::AbstractDict) at /Users/kev/.julia/packages/DataFrames/S3NqQ/src/dataframe/dataframe.jl:988
  convert(::Type{S}, ::T<:(Union{CategoricalString{R}, CategoricalValue{T,R} where T} where R)) where {S, T<:(Union{CategoricalString{R}, CategoricalValue{T,R} where T} where R)} at /Users/kev/.julia/packages/CategoricalArrays/04bks/src/value.jl:66
  ...
Stacktrace:
 [1] DataFrame(::CSV.File{NamedTuple{(:iamc_id, :age_start_smoking, :age_stopped_smoking, :alcohol_units_week, :anti_ccp_range, :anti_ccp_status, :anti_ccp_value, :asdas_crp, :basdai, :bmi, :crp, :current_alcohol_intake, :dactylitis, :das28_crp, :das28_esr, :diagnosis_at_time_of_asses, :disease_duration_at_time, :enthesitis, :esr, :ethnicity, :final_diagnosis, :final_outcome, :gender, :height_cm, :hla_b27, :ibd, :no_of_cigarettes_per_day, :patient_parents_global_vas, :peripheral_arthritis, :psoriasis, :rf_range, :rf_status, :rf_value, :sjc66, :sjc_28, :smoking_current_ever_never, :smoking_pack_years, :smoking_status, :tjc68, :tjc_28, :uveitis, :weight_kg, :diagnosis),Tuple{Union{Missing, String},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Float64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, String},Union{Missing, String},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, String},Union{Missing, Float64},Union{Missing, String},Union{Missing, Float64},Union{Missing, Int64},Union{Missing, String},Union{Missing, String},Union{Missing, String},Union{Missing, Float64},Union{Missing, String},Union{Missing, String},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, String},Union{Missing, String},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Float64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, String},Union{Missing, Float64},Union{Missing, String}}},false,Base.GenericIOBuffer{Array{UInt8,1}},Parsers.Delimited{Parsers.Quoted{Parsers.Strip{Parsers.Sentinel{typeof(Parsers.defaultparser),Parsers.Trie{0x00,false,missing,2,Tuple{}}}}},Parsers.Trie{0x00,false,missing,8,Tuple{Parsers.Trie{0x2c,true,missing,8,Tuple{}},Parsers.Trie{0x0a,true,missing,8,Tuple{}},Parsers.Trie{0x0d,true,missing,8,Tuple{Parsers.Trie{0x0a,true,missing,8,Tuple{}}}}}}},NamedTuple{(),Tuple{}}}) at /Users/kev/.julia/packages/IterableTables/Jkq8l/src/integrations/dataframes.jl:24
 [2] |>(::CSV.File{NamedTuple{(:iamc_id, :age_start_smoking, :age_stopped_smoking, :alcohol_units_week, :anti_ccp_range, :anti_ccp_status, :anti_ccp_value, :asdas_crp, :basdai, :bmi, :crp, :current_alcohol_intake, :dactylitis, :das28_crp, :das28_esr, :diagnosis_at_time_of_asses, :disease_duration_at_time, :enthesitis, :esr, :ethnicity, :final_diagnosis, :final_outcome, :gender, :height_cm, :hla_b27, :ibd, :no_of_cigarettes_per_day, :patient_parents_global_vas, :peripheral_arthritis, :psoriasis, :rf_range, :rf_status, :rf_value, :sjc66, :sjc_28, :smoking_current_ever_never, :smoking_pack_years, :smoking_status, :tjc68, :tjc_28, :uveitis, :weight_kg, :diagnosis),Tuple{Union{Missing, String},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Float64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, String},Union{Missing, String},Union{Missing, Float64},Union{Missing, Float64},Union{Missing, String},Union{Missing, Float64},Union{Missing, String},Union{Missing, Float64},Union{Missing, Int64},Union{Missing, String},Union{Missing, String},Union{Missing, String},Union{Missing, Float64},Union{Missing, String},Union{Missing, String},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, String},Union{Missing, String},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Float64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, Int64},Union{Missing, String},Union{Missing, Float64},Union{Missing, String}}},false,Base.GenericIOBuffer{Array{UInt8,1}},Parsers.Delimited{Parsers.Quoted{Parsers.Strip{Parsers.Sentinel{typeof(Parsers.defaultparser),Parsers.Trie{0x00,false,missing,2,Tuple{}}}}},Parsers.Trie{0x00,false,missing,8,Tuple{Parsers.Trie{0x2c,true,missing,8,Tuple{}},Parsers.Trie{0x0a,true,missing,8,Tuple{}},Parsers.Trie{0x0d,true,missing,8,Tuple{Parsers.Trie{0x0a,true,missing,8,Tuple{}}}}}}},NamedTuple{(),Tuple{}}}, ::Type) at ./operators.jl:813
 [3] top-level scope at none:0
 [4] #25 at ./boot.jl:319 [inlined]
 [5] with_logstate(::getfield(Main, Symbol("##25#27")), ::Base.CoreLogging.LogState) at ./logging.jl:397
 [6] with_logger(::Function, ::Atom.Progress.JunoProgressLogger) at ./logging.jl:493
 [7] top-level scope at /Users/kev/.julia/packages/Atom/jodeb/src/repl.jl:128
```

I'm quite confused, but would appreciate any assistance.

**Comment by piever** [comment] 2018-08-29 15:42
The part that I find puzzling is that the only possible interaction with StatPlots is due to StatPlots loading:

```julia
import IterableTables
import DataValues: DataValue
import TableTraits: getiterator, isiterabletable
import TableTraitsUtils: create_columns_from_iterabletable
```
as there is some type piracy involved in these packages, but somehow loading IterableTables separately didn't seem to be enough to reproduce the issue.

**Comment by quinnj** [comment] 2018-08-29 15:43
That last error seems to suggest that StatsPlots is loading IterableTables through some dependency, which is overwriting the DataFrames Tables.jl constructor. I would appreciate seeing the file so I can take a look at it on my end.

**Comment by kescobo** [comment] 2018-08-29 16:11
@quinnj Just shared link to the file via slack.

**Comment by davidanthoff** [comment] 2018-08-29 16:54
Yeah, it is no surprise that ``master`` doesn't work: the current Tables.jl implementation pretty thoroughly breaks Queryverse in lots of places. I have very little time right now, but I think that is something we certainly need to fix before Tables.jl gets released widely.

**Comment by davidanthoff** [comment] 2018-08-29 19:16
All I meant was that if you use the current Tables.jl/DataFrames.jl dev combo and Queryverse.jl, a lot of things on the Quervyerse.jl side of things stop working and that we need to figure out how to fix that before this gets released, and that we know about that. I said nothing about you not trying to find a solution (I know you are!).

**Comment by LeoK987** [comment] 2018-08-29 23:31
To me, this is related to [this](https://github.com/JuliaData/CSV.jl/issues/236#issuecomment-412448869)

**Comment by quinnj** [comment] 2018-08-30 05:32
I can confirm this is fixed on the julia nightly binary (i.e. it hangs for me on 1.0, same sequence doesn't hang on nightly). I'll try to lobby for the next Julia release to happen sooner rather than later.

**Closed by quinnj** 2018-08-30 05:32 UTC
