### ISSUE TITLE
CSV.read EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by clintonTE** [JuliaData/CSV.jl#274] opened 2018-09-13 04:57 UTC
Moving from discourse.  I got the following error calling CSV read. Note that it fails even in a try block. I just ran it again so it may look slightly different from the discourse post.

While it reproduces consistently, the code to produce typeDict is long and sprawling. Reading all the columns as Strings does not reproduce the error. Here is a snippit of the code. I can provide more if requested. The types in typeDict are Float64, Int, CategoricalValue, and the Union{Missing, } equivalents.

```
iStream = iStreamer(inPath)
  df::DataFrame = CSV.read(iStream, strings=:raw, categorical=false, rows=2)
  close(iStream)

  #get the column names and make sure each one is in the list of columns we want
  actualCols::Vector{String} = (s::Symbol->lowercase(string(s))).(names(df))

  #form the lookup dictionary for the type. Takes a column name and gets the type, with a default of String
  typeDict::Dict = Dict(
    actualCols[i] => (
    haskey(meta.dictionary, Symbol(actualCols[i])) ? meta.dictionary[Symbol(actualCols[i])]: Union{String, Missing})
    for i::Int ∈ 1:(length(actualCols)))

  #now read in the file
  iStream = iStreamer(inPath)
  df = CSV.read(iStream, header=actualCols, datarow=2, types=typeDict)
  close(iStream)
```

The data file is public and available at:
https://nccs-data.urban.org/data/core/2013/nccs.core2013pc.csv

My code uses a file with some of the metadata to produce a dictionary, which is then used to type the fields.

NOTE: I was able to workaround this issue by reading in all the columns as strings and parsing them to the correct type.  This workaround is fine for my purposes, so this post is purely informative. I really appreciate the work of the community, so hopefully this is helpful.

Error message:
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6b5c574f -- jl_new_structv at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\datatype.c:678
while loading C:\Users\Clinton Tepper\Dropbox\Projects\Endowment Project\EndowmentScripts.jl, in expression starting on line 237
jl_new_structv at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\datatype.c:679
Type at C:\Users\Clinton Tepper\.julia\v0.6\DataStreams\src\DataStreams.jl:64
unknown function (ip: 000000000466F299)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
Type at C:\Users\Clinton Tepper\.julia\v0.6\DataStreams\src\DataStreams.jl:77
Type at C:\Users\Clinton Tepper\.julia\v0.6\DataStreams\src\DataStreams.jl:72
unknown function (ip: 00000000042EFE95)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
#Source#24 at C:\Users\Clinton Tepper\.julia\v0.6\CSV\src\Source.jl:228
unknown function (ip: 000000000466CA4F)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
Type at .\<missing>:0
#Source#23 at C:\Users\Clinton Tepper\.julia\v0.6\CSV\src\Source.jl:31
unknown function (ip: 00000000046690C6)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
Type at .\<missing>:0
#read#43 at C:\Users\Clinton Tepper\.julia\v0.6\CSV\src\Source.jl:347
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
#read at .\<missing>:0
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:41
#willFail#57 at C:\Users\Clinton Tepper\Dropbox\Projects\Endowment Project\EndowmentCode\NCCSFiles.jl:70
unknown function (ip: 00000000042C9B13)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1424 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:51
#preProcessData#105 at C:\Users\Clinton Tepper\Dropbox\Projects\Endowment Project\EndowmentCode\EndowmentData.jl:58
unknown function (ip: 00000000042C58E3)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1424 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:51
#preProcessData at .\<missing>:0
endowmentTasks at C:\Users\Clinton Tepper\Dropbox\Projects\Endowment Project\EndowmentScripts.jl:22
unknown function (ip: 00000000042C4B93)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
do_call at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:75
eval at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:242
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:543
jl_interpret_toplevel_thunk at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:692
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:592
jl_eval_module_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:205
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:480
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\ast.c:873
include_string at .\loading.jl:522
unknown function (ip: 000000000424303A)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
do_call at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:75
eval at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:242
jl_interpret_toplevel_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:34
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:577
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:496
include_string at C:\Users\Clinton Tepper\.julia\v0.6\Compat\src\Compat.jl:88
unknown function (ip: 000000000EB966F2)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
#112 at C:\Users\Clinton Tepper\.julia\v0.6\Atom\src\eval.jl:109
withpath at C:\Users\Clinton Tepper\.julia\v0.6\CodeTools\src\utils.jl:30
unknown function (ip: 000000000424240A)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
withpath at C:\Users\Clinton Tepper\.julia\v0.6\Atom\src\eval.jl:38
unknown function (ip: 00000000042420BA)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:41
hideprompt at C:\Users\Clinton Tepper\.julia\v0.6\Atom\src\repl.jl:67
unknown function (ip: 0000000004241AA6)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
macro expansion at C:\Users\Clinton Tepper\.julia\v0.6\Atom\src\eval.jl:106 [inlined]
#110 at .\task.jl:80
unknown function (ip: 000000000EC0DF13)
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1903
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1424 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\task.c:267
Allocations: 40092793 (Pool: 40085305; Big: 7488); GC: 92
```

**Comment by nalimilan** [comment] 2018-09-13 12:37
It would be very useful to have the code to reproduce the crash, even if it's long.

**Comment by clintonTE** [comment] 2018-09-13 22:27
Not a problem. Unfortunately I couldn't simplify it that much and still have the bug reproduce.

Would you mind if I sent a dropbox link to your school address? The package code and data are about 159mb zipped.

**Comment by nalimilan** [comment] 2018-09-14 07:59
Didn't you say the data is public? I'm not sure I'll be able to look at this bug, but others may do that.

**Comment by quinnj** [comment] 2018-09-14 13:00
You can send the link to me; I'll take a look (you can use my email on my github profile)

**Comment by clintonTE** [comment] 2018-09-14 14:02
Cool, done. The data file is public (at the link), but the directory structure and metadata is specific to this program, so it will probably be easiest just to share it as a complete package.

**Comment by quinnj** [comment] 2019-04-30 16:57
Ok, I've tried reproducing this on windows, current master and everything seems to work fine, which isn't that surprising given the drastic changes in underlying data access patterns since #395. I'll close this for now, but encourage people to pipe up if they see anything fishy.

**Closed by quinnj** 2019-04-30 16:57 UTC
