### ISSUE TITLE
Parsing issue for scientific notation in v0.5

### ISSUE THREAD

**Issue by glwc** [JuliaData/CSV.jl#416] opened 2019-05-04 18:27 UTC
A change in scientific notation parsing behaviour in`CSV.jl` going from version `0.4.x` to `0.5` has occurred:

Numbers like `428.E+03` missing a digit between the `.` and `E` in scientific notation are now default parsed as a `String` instead of a `Float64`.  If the column type is forced eg. 

`types=Dict(Symbol(" S-Mises")=>Float64))` 

for the column in question, a warnings/errors like

`warnings: error parsing Float64 on row = 193959, col = 13: " 428.E+03,", error=INVALID: OK | SENTINEL | DELIMITED | INVALID_DELIMITER`

is generated for all lines that are missing digits between the `.` and the `E`. If one hand edits the source file column value in question to eg. `428.0E+03` the warning/error goes away.

I believe the `CSV.jl 0.4.x` behaviour should be restored.

Many thanks,
GC

**Comment by quinnj** [comment] 2019-05-04 21:01
Thanks for the report @glwc; unfortunately, I'm unable to reproduce this in Parsers.jl itself. Do you happen to have a file that exhibits the behavior you could share? Even if just privately w/ me so I can debug?

**Comment by quinnj** [comment] 2019-05-04 22:11
Ok, fix for this is up: https://github.com/JuliaData/Parsers.jl/pull/31

**Comment by glwc** [comment] 2019-05-04 22:12
Great I'll try tomorrow..

**Closed** 2019-05-04 22:24 UTC
