### ISSUE TITLE
CSV precompile issue

### ISSUE THREAD

**Issue by scotttbecker** [JuliaData/CSV.jl#985] opened 2022-02-21 01:17 UTC
I am getting a failure to pre compile when trying to install CSV. I have tried removing my .julia directory and reinstalling Julia to no avail. CSV is the first package that I am trying to add after reinstalling Julia. I am using a Dell XPS 9710 with the latest Windows 11 installed. I am using Julia 1.7.2.

Here is the error:

julia> using CSV
[ Info: Precompiling CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
ERROR: Failed to precompile CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b] to C:\Users\scott\.julia\compiled\v1.7\CSV\jl_2527.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base .\loading.jl:1466
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1410
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1120
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:1013
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:997

**Comment by nilshg** [comment] 2022-02-21 07:23
Duplicate of #981

**Closed** 2022-02-22 14:23 UTC
