### ISSUE TITLE
Another segmentation fault on CSV read

### ISSUE THREAD

**Issue by RobBlackwell** [JuliaData/CSV.jl#221] opened 2018-06-22 08:29 UTC
I'm now getting segmentation faults on previously working code and wonder if it's related to #213 , but I've tried both `Pkg.checkout` and  `use_mmap=false` with no luck.

Julia 0.6.3 on Ubuntu 18.04.

CSV files are are only about 24Mb in size.

```
df = CSV.read(filename,
                  header=false,
                  datarow=2)
```

```
signal (11): Segmentation fault
while loading /home/reb/.julia/v0.6/SimradEK60TestData/foo/csv2mat.jl, in expression starting on line 43
unknown function (ip: 0x7efe29ff3999)
restore_env at /buildworker/worker/package_linux64/build/src/subtype.c:172 [inlined]
exists_subtype at /buildworker/worker/package_linux64/build/src/subtype.c:965 [inlined]
forall_exists_subtype at /buildworker/worker/package_linux64/build/src/subtype.c:991
jl_subtype_env at /buildworker/worker/package_linux64/build/src/subtype.c:1045
simple_join at /buildworker/worker/package_linux64/build/src/subtype.c:363
simple_join at /buildworker/worker/package_linux64/build/src/subtype.c:349 [inlined]
var_gt at /buildworker/worker/package_linux64/build/src/subtype.c:499
subtype_tuple at /buildworker/worker/package_linux64/build/src/subtype.c:768 [inlined]
subtype at /buildworker/worker/package_linux64/build/src/subtype.c:900
forall_exists_equal at /buildworker/worker/package_linux64/build/src/subtype.c:941
subtype at /buildworker/worker/package_linux64/build/src/subtype.c:920
subtype_tuple at /buildworker/worker/package_linux64/build/src/subtype.c:768 [inlined]
subtype at /buildworker/worker/package_linux64/build/src/subtype.c:900
subtype_unionall at /buildworker/worker/package_linux64/build/src/subtype.c:571
exists_subtype at /buildworker/worker/package_linux64/build/src/subtype.c:963 [inlined]
forall_exists_subtype at /buildworker/worker/package_linux64/build/src/subtype.c:991
jl_subtype_env at /buildworker/worker/package_linux64/build/src/subtype.c:1045
jl_type_intersection_env_s at /buildworker/worker/package_linux64/build/src/subtype.c:2129
jl_typemap_intersection_node_visitor at /buildworker/worker/package_linux64/build/src/typemap.c:481
jl_typemap_intersection_visitor at /buildworker/worker/package_linux64/build/src/typemap.c:545
jl_typemap_intersection_visitor at /buildworker/worker/package_linux64/build/src/typemap.c:536
ml_matches at /buildworker/worker/package_linux64/build/src/gf.c:2380
jl_matching_methods at /buildworker/worker/package_linux64/build/src/gf.c:1614
_methods_by_ftype at ./reflection.jl:521
unknown function (ip: 0x7efe244b1804)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
abstract_call_gf_by_type at ./inference.jl:1311
unknown function (ip: 0x7efe244b3a66)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
abstract_call at ./inference.jl:1897
unknown function (ip: 0x7efe244afa6e)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
abstract_eval_call at ./inference.jl:1927
abstract_eval at ./inference.jl:1950
unknown function (ip: 0x7efe244aa9a6)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
abstract_eval at ./inference.jl:1956
unknown function (ip: 0x7efe244aa9a6)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
typeinf_work at ./inference.jl:2722
typeinf at ./inference.jl:2787
typeinf_frame at ./inference.jl:2504
typeinf_code at ./inference.jl:2583
unknown function (ip: 0x7efe244c6a6d)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
typeinf_ext at ./inference.jl:2622
unknown function (ip: 0x7efe244a5402)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1424 [inlined]
jl_apply_with_saved_exception_state at /buildworker/worker/package_linux64/build/src/rtutils.c:257
jl_type_infer at /buildworker/worker/package_linux64/build/src/gf.c:262
jl_compile_for_dispatch at /buildworker/worker/package_linux64/build/src/gf.c:1661
jl_compile_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:307 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:354 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
Type at /home/reb/.julia/v0.6/DataStreams/src/query.jl:164
unknown function (ip: 0x7efe11cf129e)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
#stream!#120 at /home/reb/.julia/v0.6/DataStreams/src/query.jl:547
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
#stream! at ./<missing>:0
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
#read#43 at /home/reb/.julia/v0.6/CSV/src/Source.jl:348
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
#read at ./<missing>:0
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1424 [inlined]
jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:51
load_echoview_matrix at /home/reb/.julia/v0.6/SimradEK60TestData/foo/csv2mat.jl:10
main at /home/reb/.julia/v0.6/SimradEK60TestData/foo/csv2mat.jl:24
unknown function (ip: 0x7efe11cc7fa2)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:75
eval at /buildworker/worker/package_linux64/build/src/interpreter.c:242
jl_interpret_toplevel_expr at /buildworker/worker/package_linux64/build/src/interpreter.c:34
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:577
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:873
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:616
include_from_node1 at ./loading.jl:576
unknown function (ip: 0x7efe24641b8b)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
include at ./sysimg.jl:14
unknown function (ip: 0x7efe244cc17b)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
process_options at ./client.jl:305
_start at ./client.jl:371
unknown function (ip: 0x7efe246507b8)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
unknown function (ip: 0x401bc8)
unknown function (ip: 0x401612)
__libc_start_main at /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
unknown function (ip: 0x4016bc)
Allocations: 24541436 (Pool: 24531047; Big: 10389); GC: 51
Segmentation fault (core dumped)
```

**Comment by nalimilan** [comment] 2018-06-23 21:04
Could you make a CSV file available somewhere to reproduce the problem?

**Comment by RobBlackwell** [comment] 2018-07-04 19:15
Apologies for the delay ...

```
wget https://github.com/EchoJulia/SimradEK60TestData.jl/raw/master/data/JR230-D2
0091215-T121917-120-cal.sv.csv
```

**Comment by davidanthoff** [comment] 2018-07-04 20:11
Until this is fixed you can use [CSVFiles.jl}(https://github.com/davidanthoff/CSVFiles.jl):

````julia
using CSVFiles, DataFrames

load("https://github.com/EchoJulia/SimradEK60TestData.jl/raw/master/data/JR230-D20091215-T121917-120-cal.sv.csv", header_exists=false, skiplines_begin=1) |> DataFrame
````
works for me. Auto column name detection doesn't work because only the first columns have names in the files, so one has to disable it entirely.

**Comment by quinnj** [comment] 2018-07-04 22:28
That backtrace looks like a julia subtyping bug to me; we should probably report it upstream.

**Comment by RobBlackwell** [comment] 2018-07-05 16:32
@davidanthoff - That workaround gets me out of a hole - thank you!

@quinnj - Do you mean that I should raise a new issue against https://github.com/JuliaLang/julia and link back to this one, please?

**Comment by quinnj** [comment] 2018-08-29 13:32
This should be fixed on master with a refactoring of internals; the new approach uses the `CSV.File(file; kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`

**Closed by quinnj** 2018-08-29 13:32 UTC
