### ISSUE TITLE
Parsing Float32 much slower than Float64

### ISSUE THREAD

**Issue by jaakkor2** [JuliaData/CSV.jl#117] opened 2017-11-27 14:36 UTC
On CSV v0.2.0, Julia v0.6.0, parsing Float32's is more than 2x slower than parsing Float64's.  Also, if some of the types is Int32, it seems to be faster to parse all as Float64 and then convert into Int32.
```julia
using DataFrames, CSV, BenchmarkTools
aa = randn(Float32, 100_000, 10)
fn_debug = "debug.csv"
CSV.write(fn_debug, convert(DataFrame, aa))
types64_debug = [Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64]
types32_debug = [Float32, Float32, Float32, Float32, Float32, Float32, Float32, Float32, Float32, Float32]
@btime data_csv32 = CSV.read(fn_debug, types=types32_debug)
#  192.573 ms (8000519 allocations: 125.91 MiB)
@btime data_csv64 = CSV.read(fn_debug, types=types64_debug, nullable=false)
#  93.242 ms (1000522 allocations: 22.91 MiB)
@btime data_csv64 = CSV.read(fn_debug, types=types64_debug)
#  81.459 ms (1000519 allocations: 22.91 MiB)
```

**Comment by jaakkor2** [comment] 2018-08-12 04:59
Closing the issue, on Julia v1.0.0 and CSV v0.3.0 there is no practical difference between parsing Float32's and Float64's.
```
julia> @btime data_csv32 = CSV.read(fn_debug, types=types32_debug)
  68.506 ms (1000781 allocations: 19.11 MiB)
julia> @btime data_csv64 = CSV.read(fn_debug, types=types64_debug, allowmissing=:none)
  66.618 ms (1000786 allocations: 22.92 MiB)
julia> @btime data_csv64 = CSV.read(fn_debug, types=types64_debug)
  66.417 ms (1000781 allocations: 22.92 MiB)
```

In the original example, CSV.write errors, opened an issue https://github.com/JuliaData/CSV.jl/issues/237

**Comment by jaakkor2** [comment] 2018-09-27 09:18
Julia v1.0.0, CSV v0.4.1 regressed a lot.  Reading Float32s is 18x slower than v0.3.0.
```
julia> @btime data_csv32 = CSV.read(fn_debug, types=types32_debug)
  1.205 s (11567462 allocations: 213.71 MiB)
julia> @btime data_csv64 = CSV.read(fn_debug, types=types64_debug)
  112.069 ms (100336 allocations: 23.11 MiB)
```

**Comment by quinnj** [comment] 2018-09-27 17:16
It's not an issue w/ all Floats, only full-precision (see comment [here](https://github.com/JuliaData/CSV.jl/issues/275#issuecomment-421617449)); closing as duplicate of https://github.com/JuliaData/Parsers.jl/issues/5

**Closed by quinnj** 2018-09-27 17:16 UTC
