### ISSUE TITLE
CSV.jl can't deal with following csv file.

### ISSUE THREAD

**Issue by K-JW** [JuliaData/CSV.jl#396] opened 2019-04-08 03:41 UTC
Now I have a ```csv``` file as follow:
![image](https://user-images.githubusercontent.com/12265263/55697066-58e6f700-59f2-11e9-9be6-887e8c6166b9.png)

And I use ```CSV.jl``` to import this file:
`df = CSV.File("./heat_flux.dat", delim=' ', 
 comment="#", ignorerepeated=true, header=1)|>DataFrame`

Then I can get a table as follow:
![image](https://user-images.githubusercontent.com/12265263/55697128-87fd6880-59f2-11e9-86bd-f2c1680fc515.png)

In fact, my ```csv``` file only have two columns, but ```CSV.jl``` think this file have three columns. I read document and can't find any useful methods. Thanks!

**Comment by nalimilan** [comment] 2019-04-08 20:06
Could you post a file to reproduce the problem?

**Comment by K-JW** [comment] 2019-04-09 02:39
> Could you post a file to reproduce the problem?

Here is my [file](https://drive.google.com/open?id=1wUfnCdPeDA4tk9oiFxcsseYIoRhcFzQd) , thanks very much.

**Comment by quinnj** [comment] 2019-04-16 13:02
With #395 , I `CSV.File` correctly parses 2 columns here. There is still an issue w/ the header though, in your arguments you say `header=1`, but the first line is `#t    heat_flux`, and `CSV.File` ignores it because it starts w/ your comment character `"#"`. You may want to remove the "#" from your file, or specify `datarow=2` and `header = [:t, :heat_flux]`.

**Comment by quinnj** [comment] 2019-04-26 21:20
Fixed in #395

**Closed by quinnj** 2019-04-26 21:20 UTC
