### ISSUE TITLE
MethodError: no method matching fuzzymatch(::Dict{Symbol, Int64}, ::QuoteNode) 

### ISSUE THREAD

**Issue by ptoche** [JuliaData/CSV.jl#824] opened 2021-04-12 06:37 UTC
Could be an issue with my misusing the package.

I'm trying to save a DataFrame containing the solution of a differential equation system. The DataFrame appears to be constructed correctly: No error message is spewed, but it is very large:

     3×100001 DataFrame
     Row │ x1       x2       x3       x4       x5       x6       x7       x8       ⋯
         │ Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  ⋯
    ─────┼──────────────────────────────────────────────────────────────────────────
       1 │     1.0  1.03987  1.07947  1.11883  1.15795  1.19683  1.23549  1.27394  ⋯
       2 │     5.0  5.01336  5.02745  5.04226  5.05779  5.07403  5.09097  5.10863
       3 │    10.0  9.97847  9.95721  9.93622  9.9155   9.89505  9.87487  9.85496
                                                               99993 columns omitted

Attempting to save the DataFrame with ``CSV.write("out.csv", df)`` produces:

    MethodError: no method matching fuzzymatch(::Dict{Symbol, Int64}, ::QuoteNode) 

Is it too large? Is it more of a problem with DifferentialEquations? or with DataFrames? Thanks!

Steps to reproduce:

    using DifferentialEquations, DataFrames, CSV

    # ODE System
    function lorenz!(du,u,p,t)
     du[1] = 10.0*(u[2]-u[1])
     du[2] = u[1]*(28.0-u[3]) - u[2]
     du[3] = u[1]*u[2] - (8/3)*u[3]
    end

    # Solve ODE
    f = ODEFunction(lorenz!, syms=[:x,:y,:z])
    prob = ODEProblem(f, [1.0, 5.0, 10.0], (0.0, 100.0))
    # sol = solve(prob)  # works
    sol = solve(prob, RK4(), adaptive = false, dt = 1e-3)   # fails

    # Save Data to CSV
    df = DataFrame(sol, :auto)
    CSV.write("out.csv", df)

**Comment by quinnj** [comment] 2021-04-12 16:09
Yeah, I'd guess this is a duplication of https://github.com/JuliaData/CSV.jl/issues/635 where we're hitting some fundamental limits of the Julia compiler. I've had some ideas on how to fix this, but still need to do the actual work. I'll see if I can prioritize the work this week.

**Comment by ptoche** [comment] 2021-04-13 01:49
I see. Anything wrong with the code below? Thanks!

    # Directory
    cd(expanduser("~/Julia/workspace/"))

    # Packages
    using DataFrames, CSV

    # Make large DataFrame
    df = DataFrame(rand(6,10^4), :auto)

    """
    Save large DataFrame to CSV
      Known limitations: Only splits by columns, irrespective of row length
    """
    function CSV_write(df, filename = "tmp.csv")
      chunk_size = 100
      # get size of dataframe
      df_size = ncol(df) * nrow(df)
      if df_size < chunk_size
        CSV.write(filename, df)
        return nothing
      end
      # split in chunks + append to CSV
      for k in 1:chunk_size:(ncol(df)-chunk_size)
        d = df[!, k:k+chunk_size]
        CSV.write(filename, d, append = true)
      end
      return nothing
    end

    # Go for it!
    CSV_write(df)

**Comment by quinnj** [comment] 2021-06-17 05:09
Closing as a duplicate of #635; I've started working on a fix for this in Tables.jl

**Closed by quinnj** 2021-06-17 05:09 UTC
