### ISSUE TITLE
Unable to write DataFrame of Arrays

### ISSUE THREAD

**Issue by rand5** [JuliaData/CSV.jl#133] opened 2017-12-08 00:35 UTC
```
using CSV, DataFrames
d = DataFrame(A=[[collect(1:1:5)]; [collect(2:2:8)]])
CSV.write("DeleteMe.csv",d)
```
Produces:
```
TypeError: streamto!: in typeassert, expected Array{Int64,1}, got DataArrays.DataArray{Array{Int64,1},1}

Stacktrace:
 [1] streamfrom at C:\Users\Cm7045\.julia\v0.6\DataStreams\src\DataStreams.jl:265 [inlined]
 [2] streamfrom at C:\Users\Cm7045\.julia\v0.6\DataStreams\src\DataStreams.jl:267 [inlined]
 [3] streamto!(::CSV.Sink, ::Type{DataStreams.Data.Field}, ::DataFrames.DataFrame, ::Type{Array{Int64,1}}, ::Type{Array{Int64,1}}, ::Int64, ::Int64, ::DataStreams.Data.Schema{true}, ::Base.#identity) at C:\Users\Cm7045\.julia\v0.6\DataStreams\src\DataStreams.jl:173
 [4] stream!(::DataFrames.DataFrame, ::Type{DataStreams.Data.Field}, ::CSV.Sink, ::DataStreams.Data.Schema{true}, ::DataStreams.Data.Schema{true}, ::Array{Function,1}) at C:\Users\Cm7045\.julia\v0.6\DataStreams\src\DataStreams.jl:187
 [5] #stream!#5(::Array{Any,1}, ::Function, ::DataFrames.DataFrame, ::Type{CSV.Sink}, ::Bool, ::Dict{Int64,Function}, ::String, ::Vararg{String,N} where N) at C:\Users\Cm7045\.julia\v0.6\DataStreams\src\DataStreams.jl:151
 [6] #write#36(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::String, ::DataFrames.DataFrame) at C:\Users\Cm7045\.julia\v0.6\CSV\src\Sink.jl:150
 [7] write(::String, ::DataFrames.DataFrame) at C:\Users\Cm7045\.julia\v0.6\CSV\src\Sink.jl:150
 [8] include_string(::String, ::String) at .\loading.jl:522
```

I was previously able to do this fine with `DataFrames.writetable`. In my actual use case I have a multi-column dataframe that I need to write to a csv file. Two of the columns consist of an array of arrays and the other columns are a mix of `String` and `Float64` and `Int64`.

**Comment by nalimilan** [comment] 2017-12-08 09:41
Duplicate of https://github.com/JuliaData/CSV.jl/issues/119.

**Closed by nalimilan** 2017-12-08 09:41 UTC
