### ISSUE TITLE
Data types: Float16 not possible?

### ISSUE THREAD

**Issue by LS64** [JuliaData/CSV.jl#532] opened 2019-11-19 09:04 UTC
Hello all.

I tried to read a .csv with types defined as
`types=[String,Float16,Float16,String]`
Well, as I later tested the cells with the typeof-function, I learned that the code ignores my input and uses Float64; basically, it not completely ignores the input, but it changes my input without any warning/info text. Is this intended?

Is there a possibility to get Float16 nice and simple - did I do something wrong?

**Comment by quinnj** [comment] 2019-11-20 00:02
Yes, currently all types are promoted to the common set: `Int64`, `Float64`, `Bool`, `Date`, `DateTime`, `Time`, or `String`, as we use a special internal encoding of these types for efficiency when parsing. We have an open issue for tracking the more specific types passed, though it should be noted that _while parsing_, the internal 8-byte types will always be used. Closing as duplicate of https://github.com/JuliaData/CSV.jl/issues/431

**Closed by quinnj** 2019-11-20 00:02 UTC
